Committed all the files to the Develop  branch
tavisca-rpandey/ShoppingCart pull request #1
Opened 2019-08-06 06:44 UTC by tavisca-rpandey

2019-08-06 09:20 UTC, tavisca-pkadam commented on ShoppingCart/ShoppingCart/CartItem.cs
> +        public Product item { get; private set; }
naming Product instance as "item" seems a bit confusing

2019-08-06 11:21 UTC, tavisca-nrajpurohit requested changes
Reviewed for naming conventions and comments.

2019-08-06 11:21 UTC, tavisca-nrajpurohit commented on ShoppingCart/ShoppingCart/Cart.cs
> +                // Constructor for the Cart objects
Unnecessary Comment! (as it was obvious that this was a constructor)
Check Shared "Shared Clean Code Doc"for Commenting Rules!

2019-08-06 11:21 UTC, tavisca-nrajpurohit commented on ShoppingCart/ShoppingCart/Discounts.cs
> +        public Dictionary<string, double> discountTable { get; private set; }
Naming Violation : Public properties/variables must be named in Pascal case.
suggestion : discountTable - > DiscountTable

2019-08-06 20:07 UTC, tavisca-agundawar commented on ShoppingCart/ShoppingCart/CartItem.cs
> +            item = new Product(product.Name,product.PricePerUnit);
Unnecessary creation of new object. item = product; should move the reference to the item object.

2019-08-08 16:43 UTC, tavisca-pkadam commented on ShoppingCart/SoppingCartXtest/UnitTest1.cs
> +    public class UnitTest1
{ClassName}Fixture

2019-08-08 16:45 UTC, tavisca-pkadam commented on ShoppingCart/SoppingCartXtest/UnitTest1.cs
> +    public class UnitTest1
Try Segregation of Tests For Different Classes

2019-08-14 08:55 UTC, merged